### ISSUE TITLE
Exception Ticking World

### ISSUE THREAD

**Issue by dankfrog** [SaemonMoki/ExtendedAnimals#37] opened 2020-06-09 20:07 UTC
Was just walking around the world and froze then crashed. 

heres the crash log - https://pastebin.com/5d5ksAAR

It's happened once before, not sure exactly what causes it. If it is an interaction with another mod I will report it to the dev of that mod. 

Thank you.

**Comment by dankfrog** [comment] 2020-06-14 13:17
happened again.

here is the crash log

https://www.pastebin.in/VwJVeCCZIO

**Comment by lamoyrl90** [comment] 2020-06-20 01:04
Similar crash. Only mods calling livingspawnEvent that we have in common are Quark and Genetic Animals. Odd.

**Comment by mx776** [comment] 2020-09-04 20:26
Same thing happened to me:
https://pastebin.com/YAd5sV1y

I too have the apotheosis.village.wanderer entry.

Happened the second time now, the first time was after 30 minutes of creating the world, the second time happened after around 15 hours of playing. When I reboot the game I can keep playing.

**Comment by SaemonMoki** [comment] 2020-09-25 10:07
Apotheosis is requiring that we do not change or hook into the wandering trader or his llamas, as we prevent the spawn of regular llamas at the time of the wandering trader spawning in, and replace them with our own. 
For now, this will have to be something we discuss with Apotheosis. In the mean time you might find the crashes _may_ not occur if you enable the spawning of vanilla llamas, but this won't be the best solution. I will see what we can do in regards to it, but the error itself is a very tricky one.

**Comment by Justen-N** [comment] 2021-02-02 00:27
It doesn't look like its just apotheosis, its something to do with how you handle the special spawn class. https://gist.github.com/Justen-N/98084389b8ecca677cd04aeb7138dc75

**Comment by SaemonMoki** [comment] 2021-02-02 01:41
> It doesn't look like its just apotheosis, its something to do with how you handle the special spawn class. https://gist.github.com/Justen-N/98084389b8ecca677cd04aeb7138dc75

Your error type is the same, but the cause is a completely different reason. Unrelated but I will still investigate.

**Comment by SaemonMoki** [comment] 2021-02-21 05:35
These should all be fixed in any 1.16 version after 0.6.12, please reopen if needed

**Closed by SaemonMoki** 2021-02-21 05:35 UTC
