### ISSUE TITLE
NullPointerException - Failed to remove any server config from tracker.

### ISSUE THREAD

**Issue by paulhlschr** [SaemonMoki/ExtendedAnimals#63] opened 2021-02-13 15:56 UTC
**Description**
After stopping the server, any server config file (e.g. the default forge-server.toml) fails to get removed from tracker. As a result the server process is not stopped successfully and needs to be SIGKILLed using Ctrl-C. On UNIX systems the server process even runs still after Ctrl-C the console manually, consuming resources in the background.

I have pivot tested my entire server pack and found out that Genetic Animals is the only mod that causes this stacktrace. It is not related one specific server config, but to every config that is loaded. During my tests it occured with Doggy Talents, CoFH Core, Better Animals Plus and Forge's own server config.

Please refer to [Better Animals Plus' #234](https://github.com/itsmeow/betteranimalsplus/issues/234) and the server logs at the end of this issue for additional info.

I have tested everything on a completely clean and fresh-installed server using the following versions:
- Minecraft Version: 1.16.4
- Forge Version: 35.1.37
- Mod Version: 1.16.4-0.6.15

After checking the changelogs for newly-released versions of your mod I concluded, that this error might still be a thing. A fix would be very nice, as server owners have trouble with this problem.

If you need any further information, please do not hesitate to send me a message. I am happy to help with this problem. This error should be able to be reproduced using a fresh Server with the versions I have stated before.

**Log Files**
- [latest.log](https://gist.github.com/paulhlschr/9158c73e18d657575615b278101d8cb6#file-latest-log)
- [debug.log](https://gist.github.com/paulhlschr/9158c73e18d657575615b278101d8cb6#file-debug-log)

**Comment by koderian** [comment] 2021-02-14 07:31
I can attest to this. Same issue

**Comment by SaemonMoki** [comment] 2021-02-19 01:40
I've tracked down the root cause, unfortunately it means we will lose some config functionality to fix this, functionality that we will not get back. This issue will take me some time to fix.

**Comment by koderian** [comment] 2021-02-22 20:31
has this been fixed in the newest update

**Comment by SaemonMoki** [comment] 2021-02-24 03:10
latest update *should* fix it, let me know if any clients ignore the server config after you've updated

**Closed by SaemonMoki** 2021-02-24 03:10 UTC
